### ISSUE TITLE
Unencoded double quotes in invalid queries to biocache

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/dashboard#94]
Dashboard seems to be making the same unencoded double-quote invalid queries to biocache that bie was doing:

```
==> /var/log/tomcat7/catalina.out <==
Nov 02, 2018 10:19:35 AM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:992)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


==> /var/log/nginx/access.log <==
203.101.224.162 - - [02/Nov/2018:10:19:35 +1100] "GET /ws/explore/groups.json?pageSize=10&q=state_conservation:\x22Endangered\x22 HTTP/1.1" 400 5 "-" "Java/1.8.0_181" "203.101.224.162" request_time=0.001 upstream_response_time=0.001 upstream_connect_time=0.000 upstream_header_time=0.001 upstream_cache_status=-
```

**Comment by nickdos** [comment]
deployed
